language: c

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libffi-dev libc6-dev libc6-dev-i386 libffi-dev:i386; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew install libffi; fi

script:
  - make all64
  - if [ $TRAVIS_OS_NAME = linux ]; then make all32; fi