jobs:
  include:
  - dist: xenial
    os: linux
  - dist: bionic
    os: linux
  - os: osx
  - os: windows
os: linux
dist: xenial
language: c
compiler: gcc

before_install:
  # Set global flags
  - export FILE_ROOT=ffikdb
  - export TESTS="True"
  # Install dependencies
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo apt-get install -y libffi-dev;
      export LD_LIBRARY_PATH=/usr/lib64:${LD_LIBRARY_PATH};
    elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
      echo "Utilize system ffi for Mac OSX.";
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      ./travis_setup.sh;
      export DL_INSTALL_DIR=cbuild/install;
      export LD_LIBRARY_PATH=${DL_INSTALL_DIR}/lib:${LD_LIBRARY_PATH};
      export FFI_INSTALL_DIR=travis_win/libffi/install;
      export LD_LIBRARY_PATH=${FFI_INSTALL_DIR}/bin:${LD_LIBRARY_PATH};
      export PATH=${DL_INSTALL_DIR}/lib:${PATH};
      export PATH=${DL_INSTALL_DIR}/bin:${PATH};
      export PATH=${FFI_INSTALL_DIR}/lib:${PATH};
      export PATH=${FFI_INSTALL_DIR}/bin:${PATH};
      echo $FFI_INSTALL_DIR;
      echo $DL_INSTALL_DIR;
    else
      echo "Unsupported OS.";
      exit 1;
    fi

  # Set OS directory and license location
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      QLIBDIR=l64;
      QLIC_KC=$L64;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      QLIBDIR=w64;
      QLIC_KC=$W64;
    else
      QLIBDIR=m64;
      QLIC_KC=$M64;
    fi
  - export QLIBDIR
  - export QLIC_KC

  # Set QHOME
  - mkdir -p qhome/${QLIBDIR}
  - export QHOME=$(pwd)/qhome
  - export PATH=${PATH}:${QHOME}/${QLIBDIR}

  # Prepare Test
  - if [[ $TESTS == True && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      curl -o ${QHOME}/q.zip -L $OD;
      unzip -d ${QHOME} ${QHOME}/q.zip;
      echo -n $QLIC_KC | base64 --decode > ${QHOME}/kc.lic;
    else
      echo "No kdb+, no tests";
    fi
  
  # Set Release Package
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
      export FILE_TAIL=".zip";
    else
      export FILE_TAIL=".tgz";
    fi
  - export FILE_NAME=${FILE_ROOT}-${TRAVIS_OS_NAME}-${TRAVIS_BRANCH}.${FILE_TAIL}

  # Build
  - mkdir build && cd build
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      cmake -G "Visual Studio 15 2017 Win64" --config Release ..;
      cmake --build . --config Release --target install;
      cd ../;
    else
      cmake ..;
      cmake --build . --config Release --target install;
      cd ../;
    fi

script:
  # Test
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      curl -fsSL -o test.q https://github.com/KxSystems/embedpy/raw/master/test.q;
      if [[ $TRAVIS_OS_NAME == "windows" ]]; then
        q test.q tests_win/ -q;
      else
        q test.q tests/ -q;
      fi
    fi
  # Build Package
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      7z a -tzip -r ${FILE_NAME} build/${FILE_ROOT};
    else
      tar -czf ${FILE_NAME} build/${FILE_ROOT};
    fi

deploy:
  provider: releases
  tokrn: ${GITHUB_APIKEY}
  file: ${FILE_NAME}
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "windows" || $TRAVIS_OS_NAME == "osx" || ($TRAVIS_OS_NAME == "linux" && $TRAVIS_DIST == "xenial")
  skip_cleanup: true