version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: 
environment:
  matrix:
  - BITS: 64
  - BITS: 32
install:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"

    mkdir \projects\ffi\win\w%BITS%

    appveyor-retry appveyor DownloadFile https://github.com/KxSystems/kdb/raw/master/w%BITS%/q.lib -FileName c:\projects\ffi\win\w%BITS%\q.lib
build_script:
- cmd: nmake /f win\Makefile all%BITS%
artifacts:
- path: w32
- path: w64
- path: ffi.q
- path: test_win.q
- path: LICENSE
- path: README.md