w64:
	cl /LD /MT /Iwin\x86-windows-static\include ffi.c win\w64\q.lib win\x64-windows-static\lib\libffi.lib win\x64-windows-static\lib\dl.lib	psapi.lib	
w32:
  cl /LD /MT /Iwin\x86-windows-static\include ffi.c win\w32\q.lib win\x86-windows-static\lib\libffi.lib win\x86-windows-static\lib\dl.lib	psapi.lib